<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="backend" nsURI="http://occiware.org/occi/infrastructure/crtp/backend/ecore"
    nsPrefix="backend">
  <eClassifiers xsi:type="ecore:EEnum" name="GuestOsIdentifiers">
    <eLiterals name="dosGuest"/>
    <eLiterals name="win31Guest" value="1"/>
    <eLiterals name="win95Guest" value="2"/>
    <eLiterals name="win98Guest" value="3"/>
    <eLiterals name="winMeGuest" value="4"/>
    <eLiterals name="winNTGuest" value="5"/>
    <eLiterals name="win2000ProGuest" value="6"/>
    <eLiterals name="win2000ServGuest" value="7"/>
    <eLiterals name="win2000AdvServGuest" value="8"/>
    <eLiterals name="winXPHomeGuest" value="9"/>
    <eLiterals name="winXPProGuest" value="10"/>
    <eLiterals name="winXPPro64Guest" value="11"/>
    <eLiterals name="winNetWebGuest" value="12"/>
    <eLiterals name="winNetStandardGuest" value="13"/>
    <eLiterals name="winNetEnterpriseGuest" value="14"/>
    <eLiterals name="winNetDatacenterGuest" value="15"/>
    <eLiterals name="winNetBusinessGuest" value="16"/>
    <eLiterals name="winNetStandard64Guest" value="17"/>
    <eLiterals name="winNetEnterprise64Guest" value="18"/>
    <eLiterals name="winLonghornGuest" value="19"/>
    <eLiterals name="winLonghorn64Guest" value="20"/>
    <eLiterals name="winNetDatacenter64Guest" value="21"/>
    <eLiterals name="winVistaGuest" value="22"/>
    <eLiterals name="winVista64Guest" value="23"/>
    <eLiterals name="windows7Guest" value="24"/>
    <eLiterals name="windows7_64Guest" value="25"/>
    <eLiterals name="windows7Server64Guest" value="26"/>
    <eLiterals name="windows8Guest" value="27"/>
    <eLiterals name="windows8_64Guest" value="28"/>
    <eLiterals name="windows8Server64Guest" value="29"/>
    <eLiterals name="windows9Guest" value="30"/>
    <eLiterals name="windows9_64Guest" value="31"/>
    <eLiterals name="windows9Server64Guest" value="32"/>
    <eLiterals name="windowsHyperVGuest" value="33"/>
    <eLiterals name="freebsdGuest" value="34"/>
    <eLiterals name="freebsd64Guest" value="35"/>
    <eLiterals name="redhatGuest" value="36"/>
    <eLiterals name="rhel2Guest" value="37"/>
    <eLiterals name="rhel3Guest" value="38"/>
    <eLiterals name="rhel3_64Guest" value="39"/>
    <eLiterals name="rhel4Guest" value="40"/>
    <eLiterals name="rhel4_64Guest" value="41"/>
    <eLiterals name="rhel5Guest" value="42"/>
    <eLiterals name="rhel5_64Guest" value="43"/>
    <eLiterals name="rhel6Guest" value="44"/>
    <eLiterals name="rhel6_64Guest" value="45"/>
    <eLiterals name="rhel7Guest" value="46"/>
    <eLiterals name="rhel7_64Guest" value="47"/>
    <eLiterals name="centosGuest" value="48"/>
    <eLiterals name="centos64Guest" value="49"/>
    <eLiterals name="oracleLinuxGuest" value="50"/>
    <eLiterals name="oracleLinux64Guest" value="51"/>
    <eLiterals name="suseGuest" value="52"/>
    <eLiterals name="suse64Guest" value="53"/>
    <eLiterals name="slesGuest" value="54"/>
    <eLiterals name="sles64Guest" value="55"/>
    <eLiterals name="sles10Guest" value="56"/>
    <eLiterals name="sles10_64Guest" value="57"/>
    <eLiterals name="sles11Guest" value="58"/>
    <eLiterals name="sles11_64Guest" value="59"/>
    <eLiterals name="sles12Guest" value="60"/>
    <eLiterals name="sles12_64Guest" value="61"/>
    <eLiterals name="nld9Guest" value="62"/>
    <eLiterals name="oesGuest" value="63"/>
    <eLiterals name="sjdsGuest" value="64"/>
    <eLiterals name="mandrakeGuest" value="65"/>
    <eLiterals name="mandrivaGuest" value="66"/>
    <eLiterals name="mandriva64Guest" value="67"/>
    <eLiterals name="turboLinuxGuest" value="68"/>
    <eLiterals name="turboLinux64Guest" value="69"/>
    <eLiterals name="ubuntuGuest" value="70"/>
    <eLiterals name="ubuntu64Guest" value="71"/>
    <eLiterals name="debian4Guest" value="72"/>
    <eLiterals name="debian4_64Guest" value="73"/>
    <eLiterals name="debian5Guest" value="74"/>
    <eLiterals name="debian5_64Guest" value="75"/>
    <eLiterals name="debian6Guest" value="76"/>
    <eLiterals name="debian6_64Guest" value="77"/>
    <eLiterals name="debian7Guest" value="78"/>
    <eLiterals name="debian7_64Guest" value="79"/>
    <eLiterals name="debian8Guest" value="80"/>
    <eLiterals name="debian8_64Guest" value="81"/>
    <eLiterals name="asianux3Guest" value="82"/>
    <eLiterals name="asianux3_64Guest" value="83"/>
    <eLiterals name="asianux4Guest" value="84"/>
    <eLiterals name="asianux4_64Guest" value="85"/>
    <eLiterals name="asianux5_64Guest" value="86"/>
    <eLiterals name="opensuseGuest" value="87"/>
    <eLiterals name="opensuse64Guest" value="88"/>
    <eLiterals name="fedoraGuest" value="89"/>
    <eLiterals name="fedora64Guest" value="90"/>
    <eLiterals name="coreos64Guest" value="91"/>
    <eLiterals name="other24xLinuxGuest" value="92"/>
    <eLiterals name="other26xLinuxGuest" value="93"/>
    <eLiterals name="otherLinuxGuest" value="94"/>
    <eLiterals name="other3xLinuxGuest" value="95"/>
    <eLiterals name="genericLinuxGuest" value="96"/>
    <eLiterals name="other24xLinux64Guest" value="97"/>
    <eLiterals name="other26xLinux64Guest" value="98"/>
    <eLiterals name="other3xLinux64Guest" value="99"/>
    <eLiterals name="otherLinux64Guest" value="100"/>
    <eLiterals name="solaris6Guest" value="101"/>
    <eLiterals name="solaris7Guest" value="102"/>
    <eLiterals name="solaris8Guest" value="103"/>
    <eLiterals name="solaris9Guest" value="104"/>
    <eLiterals name="solaris10Guest" value="105"/>
    <eLiterals name="solaris10_64Guest" value="106"/>
    <eLiterals name="solaris11_64Guest" value="107"/>
    <eLiterals name="os2Guest" value="108"/>
    <eLiterals name="eComStationGuest" value="109"/>
    <eLiterals name="eComStation2Guest" value="110"/>
    <eLiterals name="netware4Guest" value="111"/>
    <eLiterals name="netware5Guest" value="112"/>
    <eLiterals name="netware6Guest" value="113"/>
    <eLiterals name="openServer5Guest" value="114"/>
    <eLiterals name="openServer6Guest" value="115"/>
    <eLiterals name="unixWare7Guest" value="116"/>
    <eLiterals name="darwinGuest" value="117"/>
    <eLiterals name="darwin64Guest" value="118"/>
    <eLiterals name="darwin10Guest" value="119"/>
    <eLiterals name="darwin10_64Guest" value="120"/>
    <eLiterals name="darwin11Guest" value="121"/>
    <eLiterals name="darwin11_64Guest" value="122"/>
    <eLiterals name="darwin12_64Guest" value="123"/>
    <eLiterals name="darwin13_64Guest" value="124"/>
    <eLiterals name="darwin14_64Guest" value="125"/>
    <eLiterals name="vmkernelGuest" value="126"/>
    <eLiterals name="vmkernel5Guest" value="127"/>
    <eLiterals name="vmkernel6Guest" value="128"/>
    <eLiterals name="otherGuest" value="129"/>
    <eLiterals name="otherGuest64" value="130"/>
  </eClassifiers>
</ecore:EPackage>
