/*
 * generated by Xtext
 */
package org.occiware.clouddesigner.occi.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OCCIUiModule extends org.occiware.clouddesigner.occi.xtext.ui.AbstractOCCIUiModule {
	public OCCIUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
