/**
 * generated by Xtext
 */
package org.occiware.clouddesigner.occi.xtext.serializer;

import org.occiware.clouddesigner.occi.xtext.serializer.AbstractOCCISemanticSequencer;

@SuppressWarnings("all")
public class OCCISemanticSequencer extends AbstractOCCISemanticSequencer {
}
