/**
 * generated by Xtext
 */
package org.occiware.clouddesigner.occi.xtext.serializer;

import org.occiware.clouddesigner.occi.xtext.serializer.AbstractOCCISyntacticSequencer;

@SuppressWarnings("all")
public class OCCISyntacticSequencer extends AbstractOCCISyntacticSequencer {
}
