#! /bin/sh
#
# Generated at Sun Nov 01 21:40:09 CET 2015 from platform:/resource/org.occiware.clouddesigner.occi.erocci.samples/config/occi/infrastructure.occic by org.occiware.clouddesigner.occi.gen.curl
#

OCCI_SERVER_URL=$1
CURL_OPTS="-s -v -i"

curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/compute/vm1 -H 'Content-Type: text/occi' -H 'Category: compute; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.compute.hostname="vm1"' -H 'X-OCCI-Attribute: occi.compute.architecture="x64"' -H 'X-OCCI-Attribute: occi.compute.cores=4' -H 'X-OCCI-Attribute: occi.compute.memory=4'
curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/compute/vm2 -H 'Content-Type: text/occi' -H 'Category: compute; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.compute.hostname="vm2"' -H 'X-OCCI-Attribute: occi.compute.architecture="x64"' -H 'X-OCCI-Attribute: occi.compute.cores=2' -H 'X-OCCI-Attribute: occi.compute.memory=16'
curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/storage/storage1 -H 'Content-Type: text/occi' -H 'Category: storage; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.storage.size=100000'
curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/network/network1 -H 'Content-Type: text/occi' -H 'Category: network; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind", ipnetwork; scheme="http://schemas.ogf.org/occi/infrastructure/network#"; class="mixin";' -H 'X-OCCI-Attribute: occi.network.vlan=12' -H 'X-OCCI-Attribute: occi.network.label="private"' -H 'X-OCCI-Attribute: occi.network.address="10.1.0.0/16"' -H 'X-OCCI-Attribute: occi.network.gateway="10.1.255.254"'

curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/networkinterface/ni1 -H 'Content-Type: text/occi' -H 'Category: networkinterface; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind", ipnetworkinterface; scheme="http://schemas.ogf.org/occi/infrastructure/networkinterface#"; class="mixin";' -H 'X-OCCI-Attribute: occi.networkinterface.mac="aa:bb:cc:dd:ee:11"' -H 'X-OCCI-Attribute: occi.networkinterface.interface="eth0"' -H 'X-OCCI-Attribute: occi.networkinterface.address="10.1.0.100/16"' -H 'X-OCCI-Attribute: occi.networkinterface.gateway="10.1.255.254"' -H 'X-OCCI-Attribute: occi.networkinterface.allocation="static"' -H 'X-OCCI-Attribute: occi.core.source="/compute/vm1", occi.core.target="/network/network1"'
curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/storagelink/sl1 -H 'Content-Type: text/occi' -H 'Category: storagelink; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.storagelink.deviceid="nfs:..."' -H 'X-OCCI-Attribute: occi.storagelink.mountpoint="/mnt/scratch"' -H 'X-OCCI-Attribute: occi.core.source="/compute/vm1", occi.core.target="/storage/storage1"'
curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/storagelink/sl2 -H 'Content-Type: text/occi' -H 'Category: storagelink; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.storagelink.deviceid="nfs:..."' -H 'X-OCCI-Attribute: occi.storagelink.mountpoint="/mnt/scratch"' -H 'X-OCCI-Attribute: occi.core.source="/compute/vm2", occi.core.target="/storage/storage1"'
curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/networkinterface/ni2 -H 'Content-Type: text/occi' -H 'Category: networkinterface; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind", ipnetworkinterface; scheme="http://schemas.ogf.org/occi/infrastructure/networkinterface#"; class="mixin";' -H 'X-OCCI-Attribute: occi.networkinterface.mac="aa:bb:cc:dd:ee:12"' -H 'X-OCCI-Attribute: occi.networkinterface.interface="eth0"' -H 'X-OCCI-Attribute: occi.networkinterface.address="10.1.0.101/16"' -H 'X-OCCI-Attribute: occi.networkinterface.gateway="10.1.255.254"' -H 'X-OCCI-Attribute: occi.networkinterface.allocation="static"' -H 'X-OCCI-Attribute: occi.core.source="/compute/vm2", occi.core.target="/network/network1"'

