#! /bin/sh
#
# Generated at Mon Apr 25 17:50:14 CEST 2016 from platform:/resource/org.occiware.clouddesigner.occi.erocci.samples/config/occi/infrastructure.occic by org.occiware.clouddesigner.occi.gen.curl
#

OCCI_SERVER_URL=$1
CURL_OPTS="-s -v -i"

curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/compute/f88486b7-0632-482d-a184-a9195733ddd9 -H 'Content-Type: text/occi' -H 'Category: compute; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.core.id="f88486b7-0632-482d-a184-a9195733ddd9"' -H 'X-OCCI-Attribute: occi.core.title="vm1"' -H 'X-OCCI-Attribute: occi.core.summary="A first computer."' -H 'X-OCCI-Attribute: occi.compute.hostname="vm1"' -H 'X-OCCI-Attribute: occi.compute.architecture="x64"' -H 'X-OCCI-Attribute: occi.compute.cores=4' -H 'X-OCCI-Attribute: occi.compute.memory=4'
curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/compute/4bb03e40-4b7e-49c6-bf86-5e8ba89e8bdd -H 'Content-Type: text/occi' -H 'Category: compute; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.core.id="4bb03e40-4b7e-49c6-bf86-5e8ba89e8bdd"' -H 'X-OCCI-Attribute: occi.core.title="vm2"' -H 'X-OCCI-Attribute: occi.core.summary="A second computer."' -H 'X-OCCI-Attribute: occi.compute.hostname="vm2"' -H 'X-OCCI-Attribute: occi.compute.architecture="x64"' -H 'X-OCCI-Attribute: occi.compute.cores=2' -H 'X-OCCI-Attribute: occi.compute.memory=16'
curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/storage/50507bad-d0e9-4b6d-bc7c-e4f4c0d71dd6 -H 'Content-Type: text/occi' -H 'Category: storage; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.core.id="50507bad-d0e9-4b6d-bc7c-e4f4c0d71dd6"' -H 'X-OCCI-Attribute: occi.core.title="storage1"' -H 'X-OCCI-Attribute: occi.storage.size=100000'
curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/network/6c98d6b2-70ab-45f3-83fa-d21a7a6e7cce -H 'Content-Type: text/occi' -H 'Category: network; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind", ipnetwork; scheme="http://schemas.ogf.org/occi/infrastructure/network#"; class="mixin";' -H 'X-OCCI-Attribute: occi.core.id="6c98d6b2-70ab-45f3-83fa-d21a7a6e7cce"' -H 'X-OCCI-Attribute: occi.core.title="network1"' -H 'X-OCCI-Attribute: occi.network.vlan=12' -H 'X-OCCI-Attribute: occi.network.label="private"' -H 'X-OCCI-Attribute: occi.network.address="10.1.0.0/16"' -H 'X-OCCI-Attribute: occi.network.gateway="10.1.255.254"'

curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/networkinterface/6e7c3417-7efd-4b24-83e6-abf021bdacc1 -H 'Content-Type: text/occi' -H 'Category: networkinterface; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind", ipnetworkinterface; scheme="http://schemas.ogf.org/occi/infrastructure/networkinterface#"; class="mixin";' -H 'X-OCCI-Attribute: occi.core.id="6e7c3417-7efd-4b24-83e6-abf021bdacc1"' -H 'X-OCCI-Attribute: occi.core.title="ni1"' -H 'X-OCCI-Attribute: occi.networkinterface.mac="aa:bb:cc:dd:ee:11"' -H 'X-OCCI-Attribute: occi.networkinterface.interface="eth0"' -H 'X-OCCI-Attribute: occi.networkinterface.address="10.1.0.100/16"' -H 'X-OCCI-Attribute: occi.networkinterface.gateway="10.1.255.254"' -H 'X-OCCI-Attribute: occi.networkinterface.allocation="static"' -H 'X-OCCI-Attribute: occi.core.source="/compute/f88486b7-0632-482d-a184-a9195733ddd9", occi.core.target="/network/6c98d6b2-70ab-45f3-83fa-d21a7a6e7cce"'
curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/storagelink/850ef9f4-6eda-4519-a630-08b085fa0617 -H 'Content-Type: text/occi' -H 'Category: storagelink; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.core.id="850ef9f4-6eda-4519-a630-08b085fa0617"' -H 'X-OCCI-Attribute: occi.core.title="sl1"' -H 'X-OCCI-Attribute: occi.storagelink.deviceid="nfs:..."' -H 'X-OCCI-Attribute: occi.storagelink.mountpoint="/mnt/scratch"' -H 'X-OCCI-Attribute: occi.core.source="/compute/f88486b7-0632-482d-a184-a9195733ddd9", occi.core.target="/storage/50507bad-d0e9-4b6d-bc7c-e4f4c0d71dd6"'
curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/storagelink/1ec8f2f6-535b-4c35-b0f2-79a6adb748d0 -H 'Content-Type: text/occi' -H 'Category: storagelink; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.core.id="1ec8f2f6-535b-4c35-b0f2-79a6adb748d0"' -H 'X-OCCI-Attribute: occi.core.title="sl2"' -H 'X-OCCI-Attribute: occi.storagelink.deviceid="nfs:..."' -H 'X-OCCI-Attribute: occi.storagelink.mountpoint="/mnt/scratch"' -H 'X-OCCI-Attribute: occi.core.source="/compute/4bb03e40-4b7e-49c6-bf86-5e8ba89e8bdd", occi.core.target="/storage/50507bad-d0e9-4b6d-bc7c-e4f4c0d71dd6"'
curl $CURL_OPTS -X PUT $OCCI_SERVER_URL/networkinterface/a83fff1e-bd9a-4ce2-a182-47db4a1d1b75 -H 'Content-Type: text/occi' -H 'Category: networkinterface; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind", ipnetworkinterface; scheme="http://schemas.ogf.org/occi/infrastructure/networkinterface#"; class="mixin";' -H 'X-OCCI-Attribute: occi.core.id="a83fff1e-bd9a-4ce2-a182-47db4a1d1b75"' -H 'X-OCCI-Attribute: occi.core.title="ni2"' -H 'X-OCCI-Attribute: occi.networkinterface.mac="aa:bb:cc:dd:ee:12"' -H 'X-OCCI-Attribute: occi.networkinterface.interface="eth0"' -H 'X-OCCI-Attribute: occi.networkinterface.address="10.1.0.101/16"' -H 'X-OCCI-Attribute: occi.networkinterface.gateway="10.1.255.254"' -H 'X-OCCI-Attribute: occi.networkinterface.allocation="static"' -H 'X-OCCI-Attribute: occi.core.source="/compute/4bb03e40-4b7e-49c6-bf86-5e8ba89e8bdd", occi.core.target="/network/6c98d6b2-70ab-45f3-83fa-d21a7a6e7cce"'

