<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Container" nsURI="http://occiware.ow2.org/occi/container" nsPrefix="c">
  <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="OCCI.ecore#//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Depends" eSuperTypes="OCCI.ecore#//Link"/>
  <eClassifiers xsi:type="ecore:EClass" name="Conflicts" eSuperTypes="OCCI.ecore#//Link"/>
  <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="OCCI.ecore#//Link"/>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="OCCI.ecore#//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="OCCI.ecore#//Resource"/>
</ecore:EPackage>
