<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="servicelevelagreements" nsURI="http://schemas.ogf.org/occi/sla/ecore"
    nsPrefix="servicelevelagreements">
  <eClassifiers xsi:type="ecore:EDataType" name="DateTime" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="pattern" value="^(\d{4}((-)?(0[1-9]|1[0-2])((-)?(0[1-9]|[1-2][0-9]|3[0-1])(T(24:00(:00(\.[0]+)?)?|(([0-1][0-9]|2[0-3])(:)[0-5][0-9])((:)[0-5][0-9](\.[\d]+)?)?)((\+|-)(14:00|(0[0-9]|1[0-3])(:)[0-5][0-9])|Z))?)?)?)$"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Data type for ISO8601 date time"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AgreementStatus">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Enumeration of Agreement status"/>
    </eAnnotations>
    <eLiterals name="Pending"/>
    <eLiterals name="Accepted" value="1" literal="Accepted"/>
    <eLiterals name="Rejected" value="2"/>
    <eLiterals name="Suspended" value="3"/>
    <eLiterals name="Terminated" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AgreementTermType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Enumeration of AgreementTerm types"/>
    </eAnnotations>
    <eLiterals name="SERVICE" literal="SERVICE"/>
    <eLiterals name="SLO" value="1" literal="SLO"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AgreementTermStatus">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Enumeration of AgreementTerm status"/>
    </eAnnotations>
    <eLiterals name="Undefined" literal="Undefined"/>
    <eLiterals name="Fulfilled" value="1" literal="Fulfilled"/>
    <eLiterals name="Violated" value="2" literal="Violated"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agreement" eSuperTypes="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Resource">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="A Service Level Agreement"/>
    </eAnnotations>
    <eOperations name="accept">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="reject">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="suspend">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="resume">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="terminate">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" lowerBound="1" eType="#//AgreementStatus">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Current state of the instance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agreedAt" eType="#//DateTime">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The point in time when the agreement was made"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveFrom" eType="#//DateTime">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The point in time when the agreement’s effectiveness begins"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveUntil" eType="#//DateTime">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The point in time when the agreement’s effectiveness ends"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agreement_link" eSuperTypes="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Link">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Link between a SLA and its associated resource"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
