/*
 * generated by Xtext
 */
package org.occiware.clouddesigner.occi.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OCCIRuntimeModule extends org.occiware.clouddesigner.occi.xtext.AbstractOCCIRuntimeModule {

}
