<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="linkeddata" nsURI="http://occiware.org/linkeddata/ecore" nsPrefix="linkeddata">
  <eClassifiers xsi:type="ecore:EEnum" name="Lifecycle">
    <eLiterals name="draft"/>
    <eLiterals name="published" value="1" literal="published"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Robustness">
    <eLiterals name="cluster" literal="cluster"/>
    <eLiterals name="node" value="1"/>
    <eLiterals name="none" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ldproject" eSuperTypes="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Resource">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="LDProject"/>
    </eAnnotations>
    <eOperations name="publish">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="unpublish">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="update">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lifecycle" eType="#//Lifecycle">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="robustness" eType="#//Robustness">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lddatabaselink" eSuperTypes="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Link">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="LDDatabaseLink"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="database" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"
        defaultValueLiteral="datacore">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"
        defaultValueLiteral="27017">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ldprojectlink" eSuperTypes="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Link">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
