<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qos" nsURI="http://occiware.org/occi/qos/ecore" nsPrefix="qos">
  <eClassifiers xsi:type="ecore:EDataType" name="Strategy" instanceClassName="org.occiware.clouddesigner.occi.qos.Strategy">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="pattern" value=""/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
