/*
 * generated by Xtext
 */
package org.occiware.clouddesigner.occi.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.occiware.clouddesigner.occi.xtext.ui.internal.OCCIActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OCCIExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return OCCIActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return OCCIActivator.getInstance().getInjector(OCCIActivator.ORG_OCCIWARE_CLOUDDESIGNER_OCCI_XTEXT_OCCI);
	}
	
}
