/*
 * generated by Xtext
 */
package org.occiware.clouddesigner.occi.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.occiware.clouddesigner.occi.xtext.services.OCCIGrammarAccess;

public class OCCIParser extends AbstractContentAssistParser {
	
	@Inject
	private OCCIGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.occiware.clouddesigner.occi.xtext.ui.contentassist.antlr.internal.InternalOCCIParser createParser() {
		org.occiware.clouddesigner.occi.xtext.ui.contentassist.antlr.internal.InternalOCCIParser result = new org.occiware.clouddesigner.occi.xtext.ui.contentassist.antlr.internal.InternalOCCIParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGrammarAccess().getAlternatives(), "rule__Grammar__Alternatives");
					put(grammarAccess.getExtensionDeclAccess().getAlternatives_5(), "rule__ExtensionDecl__Alternatives_5");
					put(grammarAccess.getKindDeclAccess().getAlternatives_5(), "rule__KindDecl__Alternatives_5");
					put(grammarAccess.getMixinDeclAccess().getAlternatives_7(), "rule__MixinDecl__Alternatives_7");
					put(grammarAccess.getDataTypeAnnotationAccess().getAlternatives(), "rule__DataTypeAnnotation__Alternatives");
					put(grammarAccess.getQualifiedIDAccess().getAlternatives(), "rule__QualifiedID__Alternatives");
					put(grammarAccess.getExtensionDeclAccess().getGroup(), "rule__ExtensionDecl__Group__0");
					put(grammarAccess.getExtensionDeclAccess().getGroup_4(), "rule__ExtensionDecl__Group_4__0");
					put(grammarAccess.getExtensionDeclAccess().getGroup_4_2(), "rule__ExtensionDecl__Group_4_2__0");
					put(grammarAccess.getKindDeclAccess().getGroup(), "rule__KindDecl__Group__0");
					put(grammarAccess.getKindDeclAccess().getGroup_2(), "rule__KindDecl__Group_2__0");
					put(grammarAccess.getKindDeclAccess().getGroup_4(), "rule__KindDecl__Group_4__0");
					put(grammarAccess.getMixinDeclAccess().getGroup(), "rule__MixinDecl__Group__0");
					put(grammarAccess.getMixinDeclAccess().getGroup_2(), "rule__MixinDecl__Group_2__0");
					put(grammarAccess.getMixinDeclAccess().getGroup_2_2(), "rule__MixinDecl__Group_2_2__0");
					put(grammarAccess.getMixinDeclAccess().getGroup_3(), "rule__MixinDecl__Group_3__0");
					put(grammarAccess.getMixinDeclAccess().getGroup_3_2(), "rule__MixinDecl__Group_3_2__0");
					put(grammarAccess.getMixinDeclAccess().getGroup_5(), "rule__MixinDecl__Group_5__0");
					put(grammarAccess.getMixinDeclAccess().getGroup_6(), "rule__MixinDecl__Group_6__0");
					put(grammarAccess.getAttributeDeclAccess().getGroup(), "rule__AttributeDecl__Group__0");
					put(grammarAccess.getAttributeDeclAccess().getGroup_7(), "rule__AttributeDecl__Group_7__0");
					put(grammarAccess.getAttributeDeclAccess().getGroup_8(), "rule__AttributeDecl__Group_8__0");
					put(grammarAccess.getAttributeDeclAccess().getGroup_8_1(), "rule__AttributeDecl__Group_8_1__0");
					put(grammarAccess.getActionDeclAccess().getGroup(), "rule__ActionDecl__Group__0");
					put(grammarAccess.getActionDeclAccess().getGroup_3(), "rule__ActionDecl__Group_3__0");
					put(grammarAccess.getActionDeclAccess().getGroup_3_1(), "rule__ActionDecl__Group_3_1__0");
					put(grammarAccess.getActionDeclAccess().getGroup_5(), "rule__ActionDecl__Group_5__0");
					put(grammarAccess.getParameterDeclAccess().getGroup(), "rule__ParameterDecl__Group__0");
					put(grammarAccess.getParameterDeclAccess().getGroup_4(), "rule__ParameterDecl__Group_4__0");
					put(grammarAccess.getDataTypeDeclAccess().getGroup(), "rule__DataTypeDecl__Group__0");
					put(grammarAccess.getDataTypeDeclAccess().getGroup_5(), "rule__DataTypeDecl__Group_5__0");
					put(grammarAccess.getDataTypeAnnotationAccess().getGroup_0(), "rule__DataTypeAnnotation__Group_0__0");
					put(grammarAccess.getDataTypeAnnotationAccess().getGroup_1(), "rule__DataTypeAnnotation__Group_1__0");
					put(grammarAccess.getDataTypeAnnotationAccess().getGroup_2(), "rule__DataTypeAnnotation__Group_2__0");
					put(grammarAccess.getDataTypeAnnotationAccess().getGroup_3(), "rule__DataTypeAnnotation__Group_3__0");
					put(grammarAccess.getDataTypeAnnotationAccess().getGroup_4(), "rule__DataTypeAnnotation__Group_4__0");
					put(grammarAccess.getDataTypeAnnotationAccess().getGroup_5(), "rule__DataTypeAnnotation__Group_5__0");
					put(grammarAccess.getDataTypeAnnotationAccess().getGroup_6(), "rule__DataTypeAnnotation__Group_6__0");
					put(grammarAccess.getDataTypeAnnotationAccess().getGroup_7(), "rule__DataTypeAnnotation__Group_7__0");
					put(grammarAccess.getDataTypeAnnotationAccess().getGroup_8(), "rule__DataTypeAnnotation__Group_8__0");
					put(grammarAccess.getDataTypeAnnotationAccess().getGroup_9(), "rule__DataTypeAnnotation__Group_9__0");
					put(grammarAccess.getDataTypeAnnotationAccess().getGroup_10(), "rule__DataTypeAnnotation__Group_10__0");
					put(grammarAccess.getEnumTypeDeclAccess().getGroup(), "rule__EnumTypeDecl__Group__0");
					put(grammarAccess.getEnumTypeDeclAccess().getGroup_5(), "rule__EnumTypeDecl__Group_5__0");
					put(grammarAccess.getEnumLiteralDeclAccess().getGroup(), "rule__EnumLiteralDecl__Group__0");
					put(grammarAccess.getConfigurationDeclAccess().getGroup(), "rule__ConfigurationDecl__Group__0");
					put(grammarAccess.getConfigurationDeclAccess().getGroup_2(), "rule__ConfigurationDecl__Group_2__0");
					put(grammarAccess.getConfigurationDeclAccess().getGroup_2_2(), "rule__ConfigurationDecl__Group_2_2__0");
					put(grammarAccess.getResourceDeclAccess().getGroup(), "rule__ResourceDecl__Group__0");
					put(grammarAccess.getResourceDeclAccess().getGroup_4(), "rule__ResourceDecl__Group_4__0");
					put(grammarAccess.getResourceDeclAccess().getGroup_4_2(), "rule__ResourceDecl__Group_4_2__0");
					put(grammarAccess.getStateDeclAccess().getGroup(), "rule__StateDecl__Group__0");
					put(grammarAccess.getLinkDeclAccess().getGroup(), "rule__LinkDecl__Group__0");
					put(grammarAccess.getLinkDeclAccess().getGroup_4(), "rule__LinkDecl__Group_4__0");
					put(grammarAccess.getLinkDeclAccess().getGroup_4_2(), "rule__LinkDecl__Group_4_2__0");
					put(grammarAccess.getIntegerAccess().getGroup(), "rule__Integer__Group__0");
					put(grammarAccess.getExtensionDeclAccess().getNameAssignment_1(), "rule__ExtensionDecl__NameAssignment_1");
					put(grammarAccess.getExtensionDeclAccess().getSchemeAssignment_3(), "rule__ExtensionDecl__SchemeAssignment_3");
					put(grammarAccess.getExtensionDeclAccess().getImportAssignment_4_1(), "rule__ExtensionDecl__ImportAssignment_4_1");
					put(grammarAccess.getExtensionDeclAccess().getKindsAssignment_5_0(), "rule__ExtensionDecl__KindsAssignment_5_0");
					put(grammarAccess.getExtensionDeclAccess().getMixinsAssignment_5_1(), "rule__ExtensionDecl__MixinsAssignment_5_1");
					put(grammarAccess.getExtensionDeclAccess().getTypesAssignment_5_2(), "rule__ExtensionDecl__TypesAssignment_5_2");
					put(grammarAccess.getExtensionDeclAccess().getTypesAssignment_5_3(), "rule__ExtensionDecl__TypesAssignment_5_3");
					put(grammarAccess.getKindDeclAccess().getTermAssignment_1(), "rule__KindDecl__TermAssignment_1");
					put(grammarAccess.getKindDeclAccess().getParentAssignment_2_1(), "rule__KindDecl__ParentAssignment_2_1");
					put(grammarAccess.getKindDeclAccess().getTitleAssignment_4_1(), "rule__KindDecl__TitleAssignment_4_1");
					put(grammarAccess.getKindDeclAccess().getAttributesAssignment_5_0(), "rule__KindDecl__AttributesAssignment_5_0");
					put(grammarAccess.getKindDeclAccess().getActionsAssignment_5_1(), "rule__KindDecl__ActionsAssignment_5_1");
					put(grammarAccess.getMixinDeclAccess().getTermAssignment_1(), "rule__MixinDecl__TermAssignment_1");
					put(grammarAccess.getMixinDeclAccess().getDependsAssignment_2_1(), "rule__MixinDecl__DependsAssignment_2_1");
					put(grammarAccess.getMixinDeclAccess().getDependsAssignment_2_2_1(), "rule__MixinDecl__DependsAssignment_2_2_1");
					put(grammarAccess.getMixinDeclAccess().getAppliesAssignment_3_1(), "rule__MixinDecl__AppliesAssignment_3_1");
					put(grammarAccess.getMixinDeclAccess().getAppliesAssignment_3_2_1(), "rule__MixinDecl__AppliesAssignment_3_2_1");
					put(grammarAccess.getMixinDeclAccess().getSchemeAssignment_5_1(), "rule__MixinDecl__SchemeAssignment_5_1");
					put(grammarAccess.getMixinDeclAccess().getTitleAssignment_6_1(), "rule__MixinDecl__TitleAssignment_6_1");
					put(grammarAccess.getMixinDeclAccess().getAttributesAssignment_7_0(), "rule__MixinDecl__AttributesAssignment_7_0");
					put(grammarAccess.getMixinDeclAccess().getActionsAssignment_7_1(), "rule__MixinDecl__ActionsAssignment_7_1");
					put(grammarAccess.getAttributeDeclAccess().getMutableAssignment_1(), "rule__AttributeDecl__MutableAssignment_1");
					put(grammarAccess.getAttributeDeclAccess().getRequiredAssignment_2(), "rule__AttributeDecl__RequiredAssignment_2");
					put(grammarAccess.getAttributeDeclAccess().getNameAssignment_3(), "rule__AttributeDecl__NameAssignment_3");
					put(grammarAccess.getAttributeDeclAccess().getTypeAssignment_5(), "rule__AttributeDecl__TypeAssignment_5");
					put(grammarAccess.getAttributeDeclAccess().getMultiple_valuesAssignment_6(), "rule__AttributeDecl__Multiple_valuesAssignment_6");
					put(grammarAccess.getAttributeDeclAccess().getDefaultAssignment_7_1(), "rule__AttributeDecl__DefaultAssignment_7_1");
					put(grammarAccess.getAttributeDeclAccess().getDescriptionAssignment_8_1_1(), "rule__AttributeDecl__DescriptionAssignment_8_1_1");
					put(grammarAccess.getActionDeclAccess().getTermAssignment_1(), "rule__ActionDecl__TermAssignment_1");
					put(grammarAccess.getActionDeclAccess().getAttributesAssignment_3_0(), "rule__ActionDecl__AttributesAssignment_3_0");
					put(grammarAccess.getActionDeclAccess().getAttributesAssignment_3_1_1(), "rule__ActionDecl__AttributesAssignment_3_1_1");
					put(grammarAccess.getActionDeclAccess().getTitleAssignment_5_2(), "rule__ActionDecl__TitleAssignment_5_2");
					put(grammarAccess.getParameterDeclAccess().getNameAssignment_0(), "rule__ParameterDecl__NameAssignment_0");
					put(grammarAccess.getParameterDeclAccess().getTypeAssignment_2(), "rule__ParameterDecl__TypeAssignment_2");
					put(grammarAccess.getParameterDeclAccess().getMultiple_valuesAssignment_3(), "rule__ParameterDecl__Multiple_valuesAssignment_3");
					put(grammarAccess.getParameterDeclAccess().getDefaultAssignment_4_1(), "rule__ParameterDecl__DefaultAssignment_4_1");
					put(grammarAccess.getDataTypeDeclAccess().getNameAssignment_2(), "rule__DataTypeDecl__NameAssignment_2");
					put(grammarAccess.getDataTypeDeclAccess().getInstanceClassNameAssignment_4(), "rule__DataTypeDecl__InstanceClassNameAssignment_4");
					put(grammarAccess.getDataTypeDeclAccess().getEAnnotationsAssignment_5_1(), "rule__DataTypeDecl__EAnnotationsAssignment_5_1");
					put(grammarAccess.getDataTypeAnnotationsAccess().getDetailsAssignment(), "rule__DataTypeAnnotations__DetailsAssignment");
					put(grammarAccess.getDataTypeAnnotationAccess().getKeyAssignment_0_0(), "rule__DataTypeAnnotation__KeyAssignment_0_0");
					put(grammarAccess.getDataTypeAnnotationAccess().getValueAssignment_0_2(), "rule__DataTypeAnnotation__ValueAssignment_0_2");
					put(grammarAccess.getDataTypeAnnotationAccess().getKeyAssignment_1_0(), "rule__DataTypeAnnotation__KeyAssignment_1_0");
					put(grammarAccess.getDataTypeAnnotationAccess().getValueAssignment_1_2(), "rule__DataTypeAnnotation__ValueAssignment_1_2");
					put(grammarAccess.getDataTypeAnnotationAccess().getKeyAssignment_2_0(), "rule__DataTypeAnnotation__KeyAssignment_2_0");
					put(grammarAccess.getDataTypeAnnotationAccess().getValueAssignment_2_2(), "rule__DataTypeAnnotation__ValueAssignment_2_2");
					put(grammarAccess.getDataTypeAnnotationAccess().getKeyAssignment_3_0(), "rule__DataTypeAnnotation__KeyAssignment_3_0");
					put(grammarAccess.getDataTypeAnnotationAccess().getValueAssignment_3_2(), "rule__DataTypeAnnotation__ValueAssignment_3_2");
					put(grammarAccess.getDataTypeAnnotationAccess().getKeyAssignment_4_0(), "rule__DataTypeAnnotation__KeyAssignment_4_0");
					put(grammarAccess.getDataTypeAnnotationAccess().getValueAssignment_4_2(), "rule__DataTypeAnnotation__ValueAssignment_4_2");
					put(grammarAccess.getDataTypeAnnotationAccess().getKeyAssignment_5_0(), "rule__DataTypeAnnotation__KeyAssignment_5_0");
					put(grammarAccess.getDataTypeAnnotationAccess().getValueAssignment_5_2(), "rule__DataTypeAnnotation__ValueAssignment_5_2");
					put(grammarAccess.getDataTypeAnnotationAccess().getKeyAssignment_6_0(), "rule__DataTypeAnnotation__KeyAssignment_6_0");
					put(grammarAccess.getDataTypeAnnotationAccess().getValueAssignment_6_2(), "rule__DataTypeAnnotation__ValueAssignment_6_2");
					put(grammarAccess.getDataTypeAnnotationAccess().getKeyAssignment_7_0(), "rule__DataTypeAnnotation__KeyAssignment_7_0");
					put(grammarAccess.getDataTypeAnnotationAccess().getValueAssignment_7_2(), "rule__DataTypeAnnotation__ValueAssignment_7_2");
					put(grammarAccess.getDataTypeAnnotationAccess().getKeyAssignment_8_0(), "rule__DataTypeAnnotation__KeyAssignment_8_0");
					put(grammarAccess.getDataTypeAnnotationAccess().getValueAssignment_8_2(), "rule__DataTypeAnnotation__ValueAssignment_8_2");
					put(grammarAccess.getDataTypeAnnotationAccess().getKeyAssignment_9_0(), "rule__DataTypeAnnotation__KeyAssignment_9_0");
					put(grammarAccess.getDataTypeAnnotationAccess().getValueAssignment_9_2(), "rule__DataTypeAnnotation__ValueAssignment_9_2");
					put(grammarAccess.getDataTypeAnnotationAccess().getKeyAssignment_10_0(), "rule__DataTypeAnnotation__KeyAssignment_10_0");
					put(grammarAccess.getDataTypeAnnotationAccess().getValueAssignment_10_2(), "rule__DataTypeAnnotation__ValueAssignment_10_2");
					put(grammarAccess.getEnumTypeDeclAccess().getNameAssignment_2(), "rule__EnumTypeDecl__NameAssignment_2");
					put(grammarAccess.getEnumTypeDeclAccess().getELiteralsAssignment_4(), "rule__EnumTypeDecl__ELiteralsAssignment_4");
					put(grammarAccess.getEnumTypeDeclAccess().getELiteralsAssignment_5_1(), "rule__EnumTypeDecl__ELiteralsAssignment_5_1");
					put(grammarAccess.getEnumLiteralDeclAccess().getNameAssignment_1(), "rule__EnumLiteralDecl__NameAssignment_1");
					put(grammarAccess.getConfigurationDeclAccess().getUseAssignment_2_1(), "rule__ConfigurationDecl__UseAssignment_2_1");
					put(grammarAccess.getConfigurationDeclAccess().getResourcesAssignment_3(), "rule__ConfigurationDecl__ResourcesAssignment_3");
					put(grammarAccess.getResourceDeclAccess().getIdAssignment_1(), "rule__ResourceDecl__IdAssignment_1");
					put(grammarAccess.getResourceDeclAccess().getKindAssignment_3(), "rule__ResourceDecl__KindAssignment_3");
					put(grammarAccess.getResourceDeclAccess().getMixinsAssignment_4_1(), "rule__ResourceDecl__MixinsAssignment_4_1");
					put(grammarAccess.getResourceDeclAccess().getMixinsAssignment_4_2_1(), "rule__ResourceDecl__MixinsAssignment_4_2_1");
					put(grammarAccess.getResourceDeclAccess().getAttributesAssignment_6(), "rule__ResourceDecl__AttributesAssignment_6");
					put(grammarAccess.getResourceDeclAccess().getLinksAssignment_7(), "rule__ResourceDecl__LinksAssignment_7");
					put(grammarAccess.getStateDeclAccess().getNameAssignment_1(), "rule__StateDecl__NameAssignment_1");
					put(grammarAccess.getStateDeclAccess().getValueAssignment_3(), "rule__StateDecl__ValueAssignment_3");
					put(grammarAccess.getLinkDeclAccess().getIdAssignment_1(), "rule__LinkDecl__IdAssignment_1");
					put(grammarAccess.getLinkDeclAccess().getKindAssignment_3(), "rule__LinkDecl__KindAssignment_3");
					put(grammarAccess.getLinkDeclAccess().getMixinsAssignment_4_1(), "rule__LinkDecl__MixinsAssignment_4_1");
					put(grammarAccess.getLinkDeclAccess().getMixinsAssignment_4_2_1(), "rule__LinkDecl__MixinsAssignment_4_2_1");
					put(grammarAccess.getLinkDeclAccess().getTargetAssignment_6(), "rule__LinkDecl__TargetAssignment_6");
					put(grammarAccess.getLinkDeclAccess().getAttributesAssignment_8(), "rule__LinkDecl__AttributesAssignment_8");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.occiware.clouddesigner.occi.xtext.ui.contentassist.antlr.internal.InternalOCCIParser typedParser = (org.occiware.clouddesigner.occi.xtext.ui.contentassist.antlr.internal.InternalOCCIParser) parser;
			typedParser.entryRuleGrammar();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public OCCIGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(OCCIGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
