/**
 * generated by Xtext
 */
package org.occiware.clouddesigner.occi.xtext.validation;


/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class OCCIValidator extends AbstractOCCIValidator {
}
