/*
 * generated by Xtext
 */
package org.occiware.clouddesigner.occi.xtext.parser.antlr;

import java.io.InputStream;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OCCIAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/occiware/clouddesigner/occi/xtext/parser/antlr/internal/InternalOCCI.tokens");
	}
}
