/*
 * generated by Xtext
 */
package org.occiware.clouddesigner.occi.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.occiware.clouddesigner.occi.xtext.services.OCCIGrammarAccess;

public class OCCIParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private OCCIGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.occiware.clouddesigner.occi.xtext.parser.antlr.internal.InternalOCCIParser createParser(XtextTokenStream stream) {
		return new org.occiware.clouddesigner.occi.xtext.parser.antlr.internal.InternalOCCIParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Grammar";
	}
	
	public OCCIGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(OCCIGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
