/*
 * generated by Xtext
 */
package org.occiware.clouddesigner.occi.xtext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class OCCIGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ExtensionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Extension");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExtensionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSchemeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSchemeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSchemeEStringParserRuleCall_4_0 = (RuleCall)cSchemeAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cImportKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cImportAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cImportExtensionCrossReference_5_2_0 = (CrossReference)cImportAssignment_5_2.eContents().get(0);
		private final RuleCall cImportExtensionEStringParserRuleCall_5_2_0_1 = (RuleCall)cImportExtensionCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cImportAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cImportExtensionCrossReference_5_3_1_0 = (CrossReference)cImportAssignment_5_3_1.eContents().get(0);
		private final RuleCall cImportExtensionEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cImportExtensionCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cKindsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cKindsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cKindsKindParserRuleCall_6_2_0 = (RuleCall)cKindsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cKindsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cKindsKindParserRuleCall_6_3_1_0 = (RuleCall)cKindsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMixinsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cMixinsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cMixinsMixinParserRuleCall_7_2_0 = (RuleCall)cMixinsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cMixinsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cMixinsMixinParserRuleCall_7_3_1_0 = (RuleCall)cMixinsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Extension:
		//	"Extension" name=EString "{" "scheme" scheme=EString ("import" "(" ^import+=[Extension|EString] (","
		//	^import+=[Extension|EString])* ")")? ("kinds" "{" kinds+=Kind ("," kinds+=Kind)* "}")? ("mixins" "{" mixins+=Mixin
		//	("," mixins+=Mixin)* "}")? //		('types' '{' types+=EDataType ( "," types+=EDataType)* '}' )?
		// "}";
		@Override public ParserRule getRule() { return rule; }

		//"Extension" name=EString "{" "scheme" scheme=EString ("import" "(" ^import+=[Extension|EString] (","
		//^import+=[Extension|EString])* ")")? ("kinds" "{" kinds+=Kind ("," kinds+=Kind)* "}")? ("mixins" "{" mixins+=Mixin
		//("," mixins+=Mixin)* "}")? //		('types' '{' types+=EDataType ( "," types+=EDataType)* '}' )?
		// "}"
		public Group getGroup() { return cGroup; }

		//"Extension"
		public Keyword getExtensionKeyword_0() { return cExtensionKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"scheme"
		public Keyword getSchemeKeyword_3() { return cSchemeKeyword_3; }

		//scheme=EString
		public Assignment getSchemeAssignment_4() { return cSchemeAssignment_4; }

		//EString
		public RuleCall getSchemeEStringParserRuleCall_4_0() { return cSchemeEStringParserRuleCall_4_0; }

		//("import" "(" ^import+=[Extension|EString] ("," ^import+=[Extension|EString])* ")")?
		public Group getGroup_5() { return cGroup_5; }

		//"import"
		public Keyword getImportKeyword_5_0() { return cImportKeyword_5_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }

		//^import+=[Extension|EString]
		public Assignment getImportAssignment_5_2() { return cImportAssignment_5_2; }

		//[Extension|EString]
		public CrossReference getImportExtensionCrossReference_5_2_0() { return cImportExtensionCrossReference_5_2_0; }

		//EString
		public RuleCall getImportExtensionEStringParserRuleCall_5_2_0_1() { return cImportExtensionEStringParserRuleCall_5_2_0_1; }

		//("," ^import+=[Extension|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//^import+=[Extension|EString]
		public Assignment getImportAssignment_5_3_1() { return cImportAssignment_5_3_1; }

		//[Extension|EString]
		public CrossReference getImportExtensionCrossReference_5_3_1_0() { return cImportExtensionCrossReference_5_3_1_0; }

		//EString
		public RuleCall getImportExtensionEStringParserRuleCall_5_3_1_0_1() { return cImportExtensionEStringParserRuleCall_5_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }

		//("kinds" "{" kinds+=Kind ("," kinds+=Kind)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"kinds"
		public Keyword getKindsKeyword_6_0() { return cKindsKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//kinds+=Kind
		public Assignment getKindsAssignment_6_2() { return cKindsAssignment_6_2; }

		//Kind
		public RuleCall getKindsKindParserRuleCall_6_2_0() { return cKindsKindParserRuleCall_6_2_0; }

		//("," kinds+=Kind)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//kinds+=Kind
		public Assignment getKindsAssignment_6_3_1() { return cKindsAssignment_6_3_1; }

		//Kind
		public RuleCall getKindsKindParserRuleCall_6_3_1_0() { return cKindsKindParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//("mixins" "{" mixins+=Mixin ("," mixins+=Mixin)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"mixins"
		public Keyword getMixinsKeyword_7_0() { return cMixinsKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//mixins+=Mixin
		public Assignment getMixinsAssignment_7_2() { return cMixinsAssignment_7_2; }

		//Mixin
		public RuleCall getMixinsMixinParserRuleCall_7_2_0() { return cMixinsMixinParserRuleCall_7_2_0; }

		//("," mixins+=Mixin)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//mixins+=Mixin
		public Assignment getMixinsAssignment_7_3_1() { return cMixinsAssignment_7_3_1; }

		//Mixin
		public RuleCall getMixinsMixinParserRuleCall_7_3_1_0() { return cMixinsMixinParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }

		////		('types' '{' types+=EDataType ( "," types+=EDataType)* '}' )?
		// "}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class KindElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Kind");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cKindKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTermAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTermEStringParserRuleCall_1_0 = (RuleCall)cTermAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSchemeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSchemeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSchemeEStringParserRuleCall_4_0 = (RuleCall)cSchemeAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTitleKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTitleAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_5_1_0 = (RuleCall)cTitleAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cParentKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cParentAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cParentKindCrossReference_6_1_0 = (CrossReference)cParentAssignment_6_1.eContents().get(0);
		private final RuleCall cParentKindEStringParserRuleCall_6_1_0_1 = (RuleCall)cParentKindCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAttributesKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cAttributesAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cAttributesAttributeParserRuleCall_7_2_0 = (RuleCall)cAttributesAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cAttributesAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cAttributesAttributeParserRuleCall_7_3_1_0 = (RuleCall)cAttributesAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cActionsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cActionsAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cActionsActionParserRuleCall_8_2_0 = (RuleCall)cActionsAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cActionsAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cActionsActionParserRuleCall_8_3_1_0 = (RuleCall)cActionsAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Kind:
		//	"Kind" term=EString "{" "scheme" scheme=EString ("title" title=EString)? ("parent" parent=[Kind|EString])?
		//	("attributes" "{" attributes+=Attribute ("," attributes+=Attribute)* "}")? ("actions" "{" actions+=Action (","
		//	actions+=Action)* "}")? "}";
		@Override public ParserRule getRule() { return rule; }

		//"Kind" term=EString "{" "scheme" scheme=EString ("title" title=EString)? ("parent" parent=[Kind|EString])? ("attributes"
		//"{" attributes+=Attribute ("," attributes+=Attribute)* "}")? ("actions" "{" actions+=Action ("," actions+=Action)*
		//"}")? "}"
		public Group getGroup() { return cGroup; }

		//"Kind"
		public Keyword getKindKeyword_0() { return cKindKeyword_0; }

		//term=EString
		public Assignment getTermAssignment_1() { return cTermAssignment_1; }

		//EString
		public RuleCall getTermEStringParserRuleCall_1_0() { return cTermEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"scheme"
		public Keyword getSchemeKeyword_3() { return cSchemeKeyword_3; }

		//scheme=EString
		public Assignment getSchemeAssignment_4() { return cSchemeAssignment_4; }

		//EString
		public RuleCall getSchemeEStringParserRuleCall_4_0() { return cSchemeEStringParserRuleCall_4_0; }

		//("title" title=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"title"
		public Keyword getTitleKeyword_5_0() { return cTitleKeyword_5_0; }

		//title=EString
		public Assignment getTitleAssignment_5_1() { return cTitleAssignment_5_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_5_1_0() { return cTitleEStringParserRuleCall_5_1_0; }

		//("parent" parent=[Kind|EString])?
		public Group getGroup_6() { return cGroup_6; }

		//"parent"
		public Keyword getParentKeyword_6_0() { return cParentKeyword_6_0; }

		//parent=[Kind|EString]
		public Assignment getParentAssignment_6_1() { return cParentAssignment_6_1; }

		//[Kind|EString]
		public CrossReference getParentKindCrossReference_6_1_0() { return cParentKindCrossReference_6_1_0; }

		//EString
		public RuleCall getParentKindEStringParserRuleCall_6_1_0_1() { return cParentKindEStringParserRuleCall_6_1_0_1; }

		//("attributes" "{" attributes+=Attribute ("," attributes+=Attribute)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"attributes"
		public Keyword getAttributesKeyword_7_0() { return cAttributesKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//attributes+=Attribute
		public Assignment getAttributesAssignment_7_2() { return cAttributesAssignment_7_2; }

		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_7_2_0() { return cAttributesAttributeParserRuleCall_7_2_0; }

		//("," attributes+=Attribute)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//attributes+=Attribute
		public Assignment getAttributesAssignment_7_3_1() { return cAttributesAssignment_7_3_1; }

		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_7_3_1_0() { return cAttributesAttributeParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }

		//("actions" "{" actions+=Action ("," actions+=Action)* "}")?
		public Group getGroup_8() { return cGroup_8; }

		//"actions"
		public Keyword getActionsKeyword_8_0() { return cActionsKeyword_8_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }

		//actions+=Action
		public Assignment getActionsAssignment_8_2() { return cActionsAssignment_8_2; }

		//Action
		public RuleCall getActionsActionParserRuleCall_8_2_0() { return cActionsActionParserRuleCall_8_2_0; }

		//("," actions+=Action)*
		public Group getGroup_8_3() { return cGroup_8_3; }

		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }

		//actions+=Action
		public Assignment getActionsAssignment_8_3_1() { return cActionsAssignment_8_3_1; }

		//Action
		public RuleCall getActionsActionParserRuleCall_8_3_1_0() { return cActionsActionParserRuleCall_8_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class MixinElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Mixin");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMixinKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTermAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTermEStringParserRuleCall_1_0 = (RuleCall)cTermAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSchemeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSchemeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSchemeEStringParserRuleCall_4_0 = (RuleCall)cSchemeAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTitleKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTitleAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_5_1_0 = (RuleCall)cTitleAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAttributesKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cAttributesAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cAttributesAttributeParserRuleCall_6_2_0 = (RuleCall)cAttributesAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cAttributesAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cAttributesAttributeParserRuleCall_6_3_1_0 = (RuleCall)cAttributesAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cActionsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cActionsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cActionsActionParserRuleCall_7_2_0 = (RuleCall)cActionsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cActionsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cActionsActionParserRuleCall_7_3_1_0 = (RuleCall)cActionsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Mixin:
		//	"Mixin" term=EString "{" "scheme" scheme=EString ("title" title=EString)?
		//	//		('depends' '(' depends+=[Mixin|EString] ( "," depends+=[Mixin|EString])* ')' )?
		//
		//	//		('applies' '(' applies+=[Kind|EString] ( "," applies+=[Kind|EString])* ')' )?
		// ("attributes" "{"
		//	attributes+=Attribute ("," attributes+=Attribute)* "}")? ("actions" "{" actions+=Action ("," actions+=Action)* "}")?
		//	"}";
		@Override public ParserRule getRule() { return rule; }

		//"Mixin" term=EString "{" "scheme" scheme=EString ("title" title=EString)?
		////		('depends' '(' depends+=[Mixin|EString] ( "," depends+=[Mixin|EString])* ')' )?
		//
		////		('applies' '(' applies+=[Kind|EString] ( "," applies+=[Kind|EString])* ')' )?
		// ("attributes" "{"
		//attributes+=Attribute ("," attributes+=Attribute)* "}")? ("actions" "{" actions+=Action ("," actions+=Action)* "}")?
		//"}"
		public Group getGroup() { return cGroup; }

		//"Mixin"
		public Keyword getMixinKeyword_0() { return cMixinKeyword_0; }

		//term=EString
		public Assignment getTermAssignment_1() { return cTermAssignment_1; }

		//EString
		public RuleCall getTermEStringParserRuleCall_1_0() { return cTermEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"scheme"
		public Keyword getSchemeKeyword_3() { return cSchemeKeyword_3; }

		//scheme=EString
		public Assignment getSchemeAssignment_4() { return cSchemeAssignment_4; }

		//EString
		public RuleCall getSchemeEStringParserRuleCall_4_0() { return cSchemeEStringParserRuleCall_4_0; }

		//("title" title=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"title"
		public Keyword getTitleKeyword_5_0() { return cTitleKeyword_5_0; }

		//title=EString
		public Assignment getTitleAssignment_5_1() { return cTitleAssignment_5_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_5_1_0() { return cTitleEStringParserRuleCall_5_1_0; }

		//("attributes" "{" attributes+=Attribute ("," attributes+=Attribute)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"attributes"
		public Keyword getAttributesKeyword_6_0() { return cAttributesKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//attributes+=Attribute
		public Assignment getAttributesAssignment_6_2() { return cAttributesAssignment_6_2; }

		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_6_2_0() { return cAttributesAttributeParserRuleCall_6_2_0; }

		//("," attributes+=Attribute)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//attributes+=Attribute
		public Assignment getAttributesAssignment_6_3_1() { return cAttributesAssignment_6_3_1; }

		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_6_3_1_0() { return cAttributesAttributeParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//("actions" "{" actions+=Action ("," actions+=Action)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"actions"
		public Keyword getActionsKeyword_7_0() { return cActionsKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//actions+=Action
		public Assignment getActionsAssignment_7_2() { return cActionsAssignment_7_2; }

		//Action
		public RuleCall getActionsActionParserRuleCall_7_2_0() { return cActionsActionParserRuleCall_7_2_0; }

		//("," actions+=Action)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//actions+=Action
		public Assignment getActionsAssignment_7_3_1() { return cActionsAssignment_7_3_1; }

		//Action
		public RuleCall getActionsActionParserRuleCall_7_3_1_0() { return cActionsActionParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Attribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAttributeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cMutableKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cMutableAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cMutableEBooleanParserRuleCall_3_1_0 = (RuleCall)cMutableAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRequiredKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRequiredAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cRequiredEBooleanParserRuleCall_4_1_0 = (RuleCall)cRequiredAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDefaultKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDefaultAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDefaultEStringParserRuleCall_5_1_0 = (RuleCall)cDefaultAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDescriptionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDescriptionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_6_1_0 = (RuleCall)cDescriptionAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Attribute:
		//	"Attribute" name=EString "{" ("mutable" mutable=EBoolean)? ("required" required=EBoolean)? ("default"
		//	default=EString)? ("description" description=EString)? //		('type' type=[ecore::EDataType|EString])?
		// "}";
		@Override public ParserRule getRule() { return rule; }

		//"Attribute" name=EString "{" ("mutable" mutable=EBoolean)? ("required" required=EBoolean)? ("default" default=EString)?
		//("description" description=EString)? //		('type' type=[ecore::EDataType|EString])?
		// "}"
		public Group getGroup() { return cGroup; }

		//"Attribute"
		public Keyword getAttributeKeyword_0() { return cAttributeKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("mutable" mutable=EBoolean)?
		public Group getGroup_3() { return cGroup_3; }

		//"mutable"
		public Keyword getMutableKeyword_3_0() { return cMutableKeyword_3_0; }

		//mutable=EBoolean
		public Assignment getMutableAssignment_3_1() { return cMutableAssignment_3_1; }

		//EBoolean
		public RuleCall getMutableEBooleanParserRuleCall_3_1_0() { return cMutableEBooleanParserRuleCall_3_1_0; }

		//("required" required=EBoolean)?
		public Group getGroup_4() { return cGroup_4; }

		//"required"
		public Keyword getRequiredKeyword_4_0() { return cRequiredKeyword_4_0; }

		//required=EBoolean
		public Assignment getRequiredAssignment_4_1() { return cRequiredAssignment_4_1; }

		//EBoolean
		public RuleCall getRequiredEBooleanParserRuleCall_4_1_0() { return cRequiredEBooleanParserRuleCall_4_1_0; }

		//("default" default=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"default"
		public Keyword getDefaultKeyword_5_0() { return cDefaultKeyword_5_0; }

		//default=EString
		public Assignment getDefaultAssignment_5_1() { return cDefaultAssignment_5_1; }

		//EString
		public RuleCall getDefaultEStringParserRuleCall_5_1_0() { return cDefaultEStringParserRuleCall_5_1_0; }

		//("description" description=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"description"
		public Keyword getDescriptionKeyword_6_0() { return cDescriptionKeyword_6_0; }

		//description=EString
		public Assignment getDescriptionAssignment_6_1() { return cDescriptionAssignment_6_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_6_1_0() { return cDescriptionEStringParserRuleCall_6_1_0; }

		////		('type' type=[ecore::EDataType|EString])?
		// "}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTermAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTermEStringParserRuleCall_1_0 = (RuleCall)cTermAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSchemeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSchemeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSchemeEStringParserRuleCall_4_0 = (RuleCall)cSchemeAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTitleKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTitleAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_5_1_0 = (RuleCall)cTitleAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAttributesKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cAttributesAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cAttributesAttributeParserRuleCall_6_2_0 = (RuleCall)cAttributesAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cAttributesAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cAttributesAttributeParserRuleCall_6_3_1_0 = (RuleCall)cAttributesAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Action:
		//	"Action" term=EString "{" "scheme" scheme=EString ("title" title=EString)? ("attributes" "{" attributes+=Attribute
		//	("," attributes+=Attribute)* "}")? "}";
		@Override public ParserRule getRule() { return rule; }

		//"Action" term=EString "{" "scheme" scheme=EString ("title" title=EString)? ("attributes" "{" attributes+=Attribute (","
		//attributes+=Attribute)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"Action"
		public Keyword getActionKeyword_0() { return cActionKeyword_0; }

		//term=EString
		public Assignment getTermAssignment_1() { return cTermAssignment_1; }

		//EString
		public RuleCall getTermEStringParserRuleCall_1_0() { return cTermEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"scheme"
		public Keyword getSchemeKeyword_3() { return cSchemeKeyword_3; }

		//scheme=EString
		public Assignment getSchemeAssignment_4() { return cSchemeAssignment_4; }

		//EString
		public RuleCall getSchemeEStringParserRuleCall_4_0() { return cSchemeEStringParserRuleCall_4_0; }

		//("title" title=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"title"
		public Keyword getTitleKeyword_5_0() { return cTitleKeyword_5_0; }

		//title=EString
		public Assignment getTitleAssignment_5_1() { return cTitleAssignment_5_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_5_1_0() { return cTitleEStringParserRuleCall_5_1_0; }

		//("attributes" "{" attributes+=Attribute ("," attributes+=Attribute)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"attributes"
		public Keyword getAttributesKeyword_6_0() { return cAttributesKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//attributes+=Attribute
		public Assignment getAttributesAssignment_6_2() { return cAttributesAssignment_6_2; }

		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_6_2_0() { return cAttributesAttributeParserRuleCall_6_2_0; }

		//("," attributes+=Attribute)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//attributes+=Attribute
		public Assignment getAttributesAssignment_6_3_1() { return cAttributesAssignment_6_3_1; }

		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_6_3_1_0() { return cAttributesAttributeParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class EEnumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EEnum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEEnumAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEEnumKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cInstanceClassNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cInstanceClassNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cInstanceClassNameEStringParserRuleCall_4_1_0 = (RuleCall)cInstanceClassNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cInstanceTypeNameKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cInstanceTypeNameAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cInstanceTypeNameEStringParserRuleCall_5_1_0 = (RuleCall)cInstanceTypeNameAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSerializableKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSerializableAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cSerializableEBooleanParserRuleCall_6_1_0 = (RuleCall)cSerializableAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cELiteralsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cELiteralsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cELiteralsEEnumLiteralParserRuleCall_7_2_0 = (RuleCall)cELiteralsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cELiteralsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cELiteralsEEnumLiteralParserRuleCall_7_3_1_0 = (RuleCall)cELiteralsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//EEnum returns ecore::EEnum:
		//	{ecore::EEnum} "EEnum" name=EString "{" ("instanceClassName" instanceClassName=EString)? ("instanceTypeName"
		//	instanceTypeName=EString)? ("serializable" serializable=EBoolean)? ("eLiterals" "{" eLiterals+=EEnumLiteral (","
		//	eLiterals+=EEnumLiteral)* "}")? "}";
		@Override public ParserRule getRule() { return rule; }

		//{ecore::EEnum} "EEnum" name=EString "{" ("instanceClassName" instanceClassName=EString)? ("instanceTypeName"
		//instanceTypeName=EString)? ("serializable" serializable=EBoolean)? ("eLiterals" "{" eLiterals+=EEnumLiteral (","
		//eLiterals+=EEnumLiteral)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{ecore::EEnum}
		public Action getEEnumAction_0() { return cEEnumAction_0; }

		//"EEnum"
		public Keyword getEEnumKeyword_1() { return cEEnumKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("instanceClassName" instanceClassName=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"instanceClassName"
		public Keyword getInstanceClassNameKeyword_4_0() { return cInstanceClassNameKeyword_4_0; }

		//instanceClassName=EString
		public Assignment getInstanceClassNameAssignment_4_1() { return cInstanceClassNameAssignment_4_1; }

		//EString
		public RuleCall getInstanceClassNameEStringParserRuleCall_4_1_0() { return cInstanceClassNameEStringParserRuleCall_4_1_0; }

		//("instanceTypeName" instanceTypeName=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"instanceTypeName"
		public Keyword getInstanceTypeNameKeyword_5_0() { return cInstanceTypeNameKeyword_5_0; }

		//instanceTypeName=EString
		public Assignment getInstanceTypeNameAssignment_5_1() { return cInstanceTypeNameAssignment_5_1; }

		//EString
		public RuleCall getInstanceTypeNameEStringParserRuleCall_5_1_0() { return cInstanceTypeNameEStringParserRuleCall_5_1_0; }

		//("serializable" serializable=EBoolean)?
		public Group getGroup_6() { return cGroup_6; }

		//"serializable"
		public Keyword getSerializableKeyword_6_0() { return cSerializableKeyword_6_0; }

		//serializable=EBoolean
		public Assignment getSerializableAssignment_6_1() { return cSerializableAssignment_6_1; }

		//EBoolean
		public RuleCall getSerializableEBooleanParserRuleCall_6_1_0() { return cSerializableEBooleanParserRuleCall_6_1_0; }

		//("eLiterals" "{" eLiterals+=EEnumLiteral ("," eLiterals+=EEnumLiteral)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"eLiterals"
		public Keyword getELiteralsKeyword_7_0() { return cELiteralsKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//eLiterals+=EEnumLiteral
		public Assignment getELiteralsAssignment_7_2() { return cELiteralsAssignment_7_2; }

		//EEnumLiteral
		public RuleCall getELiteralsEEnumLiteralParserRuleCall_7_2_0() { return cELiteralsEEnumLiteralParserRuleCall_7_2_0; }

		//("," eLiterals+=EEnumLiteral)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//eLiterals+=EEnumLiteral
		public Assignment getELiteralsAssignment_7_3_1() { return cELiteralsAssignment_7_3_1; }

		//EEnumLiteral
		public RuleCall getELiteralsEEnumLiteralParserRuleCall_7_3_1_0() { return cELiteralsEEnumLiteralParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class EEnumLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EEnumLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEEnumLiteralAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEEnumLiteralKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cValueKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cValueAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValueEIntParserRuleCall_4_1_0 = (RuleCall)cValueAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLiteralKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLiteralAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLiteralEStringParserRuleCall_5_1_0 = (RuleCall)cLiteralAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//EEnumLiteral returns ecore::EEnumLiteral:
		//	{ecore::EEnumLiteral} "EEnumLiteral" name=EString "{" ("value" value=EInt)? ("literal" literal=EString)? "}";
		@Override public ParserRule getRule() { return rule; }

		//{ecore::EEnumLiteral} "EEnumLiteral" name=EString "{" ("value" value=EInt)? ("literal" literal=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{ecore::EEnumLiteral}
		public Action getEEnumLiteralAction_0() { return cEEnumLiteralAction_0; }

		//"EEnumLiteral"
		public Keyword getEEnumLiteralKeyword_1() { return cEEnumLiteralKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("value" value=EInt)?
		public Group getGroup_4() { return cGroup_4; }

		//"value"
		public Keyword getValueKeyword_4_0() { return cValueKeyword_4_0; }

		//value=EInt
		public Assignment getValueAssignment_4_1() { return cValueAssignment_4_1; }

		//EInt
		public RuleCall getValueEIntParserRuleCall_4_1_0() { return cValueEIntParserRuleCall_4_1_0; }

		//("literal" literal=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"literal"
		public Keyword getLiteralKeyword_5_0() { return cLiteralKeyword_5_0; }

		//literal=EString
		public Assignment getLiteralAssignment_5_1() { return cLiteralAssignment_5_1; }

		//EString
		public RuleCall getLiteralEStringParserRuleCall_5_1_0() { return cLiteralEStringParserRuleCall_5_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class EDataType_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EDataType_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEDataTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEDataTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cInstanceClassNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cInstanceClassNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cInstanceClassNameEStringParserRuleCall_4_1_0 = (RuleCall)cInstanceClassNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cInstanceTypeNameKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cInstanceTypeNameAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cInstanceTypeNameEStringParserRuleCall_5_1_0 = (RuleCall)cInstanceTypeNameAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSerializableKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSerializableAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cSerializableEBooleanParserRuleCall_6_1_0 = (RuleCall)cSerializableAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//EDataType_Impl returns ecore::EDataType:
		//	{ecore::EDataType} "EDataType" name=EString "{" ("instanceClassName" instanceClassName=EString)? ("instanceTypeName"
		//	instanceTypeName=EString)? ("serializable" serializable=EBoolean)? "}";
		@Override public ParserRule getRule() { return rule; }

		//{ecore::EDataType} "EDataType" name=EString "{" ("instanceClassName" instanceClassName=EString)? ("instanceTypeName"
		//instanceTypeName=EString)? ("serializable" serializable=EBoolean)? "}"
		public Group getGroup() { return cGroup; }

		//{ecore::EDataType}
		public Action getEDataTypeAction_0() { return cEDataTypeAction_0; }

		//"EDataType"
		public Keyword getEDataTypeKeyword_1() { return cEDataTypeKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("instanceClassName" instanceClassName=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"instanceClassName"
		public Keyword getInstanceClassNameKeyword_4_0() { return cInstanceClassNameKeyword_4_0; }

		//instanceClassName=EString
		public Assignment getInstanceClassNameAssignment_4_1() { return cInstanceClassNameAssignment_4_1; }

		//EString
		public RuleCall getInstanceClassNameEStringParserRuleCall_4_1_0() { return cInstanceClassNameEStringParserRuleCall_4_1_0; }

		//("instanceTypeName" instanceTypeName=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"instanceTypeName"
		public Keyword getInstanceTypeNameKeyword_5_0() { return cInstanceTypeNameKeyword_5_0; }

		//instanceTypeName=EString
		public Assignment getInstanceTypeNameAssignment_5_1() { return cInstanceTypeNameAssignment_5_1; }

		//EString
		public RuleCall getInstanceTypeNameEStringParserRuleCall_5_1_0() { return cInstanceTypeNameEStringParserRuleCall_5_1_0; }

		//("serializable" serializable=EBoolean)?
		public Group getGroup_6() { return cGroup_6; }

		//"serializable"
		public Keyword getSerializableKeyword_6_0() { return cSerializableKeyword_6_0; }

		//serializable=EBoolean
		public Assignment getSerializableAssignment_6_1() { return cSerializableAssignment_6_1; }

		//EBoolean
		public RuleCall getSerializableEBooleanParserRuleCall_6_1_0() { return cSerializableEBooleanParserRuleCall_6_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class EDataTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EDataType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEDataType_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEEnumParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EDataType returns ecore::EDataType:
		//	EDataType_Impl | EEnum;
		@Override public ParserRule getRule() { return rule; }

		//EDataType_Impl | EEnum
		public Alternatives getAlternatives() { return cAlternatives; }

		//EDataType_Impl
		public RuleCall getEDataType_ImplParserRuleCall_0() { return cEDataType_ImplParserRuleCall_0; }

		//EEnum
		public RuleCall getEEnumParserRuleCall_1() { return cEEnumParserRuleCall_1; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		@Override public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		@Override public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	
	private final ExtensionElements pExtension;
	private final KindElements pKind;
	private final MixinElements pMixin;
	private final AttributeElements pAttribute;
	private final ActionElements pAction;
	private final EEnumElements pEEnum;
	private final EEnumLiteralElements pEEnumLiteral;
	private final EDataType_ImplElements pEDataType_Impl;
	private final EDataTypeElements pEDataType;
	private final EBooleanElements pEBoolean;
	private final EStringElements pEString;
	private final EIntElements pEInt;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public OCCIGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pExtension = new ExtensionElements();
		this.pKind = new KindElements();
		this.pMixin = new MixinElements();
		this.pAttribute = new AttributeElements();
		this.pAction = new ActionElements();
		this.pEEnum = new EEnumElements();
		this.pEEnumLiteral = new EEnumLiteralElements();
		this.pEDataType_Impl = new EDataType_ImplElements();
		this.pEDataType = new EDataTypeElements();
		this.pEBoolean = new EBooleanElements();
		this.pEString = new EStringElements();
		this.pEInt = new EIntElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.occiware.clouddesigner.occi.xtext.OCCI".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Extension:
	//	"Extension" name=EString "{" "scheme" scheme=EString ("import" "(" ^import+=[Extension|EString] (","
	//	^import+=[Extension|EString])* ")")? ("kinds" "{" kinds+=Kind ("," kinds+=Kind)* "}")? ("mixins" "{" mixins+=Mixin
	//	("," mixins+=Mixin)* "}")? //		('types' '{' types+=EDataType ( "," types+=EDataType)* '}' )?
	// "}";
	public ExtensionElements getExtensionAccess() {
		return pExtension;
	}
	
	public ParserRule getExtensionRule() {
		return getExtensionAccess().getRule();
	}

	//Kind:
	//	"Kind" term=EString "{" "scheme" scheme=EString ("title" title=EString)? ("parent" parent=[Kind|EString])?
	//	("attributes" "{" attributes+=Attribute ("," attributes+=Attribute)* "}")? ("actions" "{" actions+=Action (","
	//	actions+=Action)* "}")? "}";
	public KindElements getKindAccess() {
		return pKind;
	}
	
	public ParserRule getKindRule() {
		return getKindAccess().getRule();
	}

	//Mixin:
	//	"Mixin" term=EString "{" "scheme" scheme=EString ("title" title=EString)?
	//	//		('depends' '(' depends+=[Mixin|EString] ( "," depends+=[Mixin|EString])* ')' )?
	//
	//	//		('applies' '(' applies+=[Kind|EString] ( "," applies+=[Kind|EString])* ')' )?
	// ("attributes" "{"
	//	attributes+=Attribute ("," attributes+=Attribute)* "}")? ("actions" "{" actions+=Action ("," actions+=Action)* "}")?
	//	"}";
	public MixinElements getMixinAccess() {
		return pMixin;
	}
	
	public ParserRule getMixinRule() {
		return getMixinAccess().getRule();
	}

	//Attribute:
	//	"Attribute" name=EString "{" ("mutable" mutable=EBoolean)? ("required" required=EBoolean)? ("default"
	//	default=EString)? ("description" description=EString)? //		('type' type=[ecore::EDataType|EString])?
	// "}";
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}

	//Action:
	//	"Action" term=EString "{" "scheme" scheme=EString ("title" title=EString)? ("attributes" "{" attributes+=Attribute
	//	("," attributes+=Attribute)* "}")? "}";
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}

	//EEnum returns ecore::EEnum:
	//	{ecore::EEnum} "EEnum" name=EString "{" ("instanceClassName" instanceClassName=EString)? ("instanceTypeName"
	//	instanceTypeName=EString)? ("serializable" serializable=EBoolean)? ("eLiterals" "{" eLiterals+=EEnumLiteral (","
	//	eLiterals+=EEnumLiteral)* "}")? "}";
	public EEnumElements getEEnumAccess() {
		return pEEnum;
	}
	
	public ParserRule getEEnumRule() {
		return getEEnumAccess().getRule();
	}

	//EEnumLiteral returns ecore::EEnumLiteral:
	//	{ecore::EEnumLiteral} "EEnumLiteral" name=EString "{" ("value" value=EInt)? ("literal" literal=EString)? "}";
	public EEnumLiteralElements getEEnumLiteralAccess() {
		return pEEnumLiteral;
	}
	
	public ParserRule getEEnumLiteralRule() {
		return getEEnumLiteralAccess().getRule();
	}

	//EDataType_Impl returns ecore::EDataType:
	//	{ecore::EDataType} "EDataType" name=EString "{" ("instanceClassName" instanceClassName=EString)? ("instanceTypeName"
	//	instanceTypeName=EString)? ("serializable" serializable=EBoolean)? "}";
	public EDataType_ImplElements getEDataType_ImplAccess() {
		return pEDataType_Impl;
	}
	
	public ParserRule getEDataType_ImplRule() {
		return getEDataType_ImplAccess().getRule();
	}

	//EDataType returns ecore::EDataType:
	//	EDataType_Impl | EEnum;
	public EDataTypeElements getEDataTypeAccess() {
		return pEDataType;
	}
	
	public ParserRule getEDataTypeRule() {
		return getEDataTypeAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
